spring.application.name=placement-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/placement_management
spring.datasource.username=postgres
spring.datasource.password=root
jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true